/** Onboarding explanations for each methodology step named in AGE_TIERS. */
export const STEP_GUIDE: Record<string, { icon: string; text: string; example: string }> = {
  Notice: { icon: 'eye', text: 'Look carefully around you: at school, at home, at the market.', example: 'The classroom bin is always overflowing.' },
  Ask: { icon: 'help-circle', text: 'Ask questions about what you noticed. Why does it happen?', example: 'Why does the bin fill up so fast?' },
  Imagine: { icon: 'cloud', text: 'Dream up many ideas. Silly ones are welcome!', example: 'A bin that squashes rubbish by itself.' },
  Draw: { icon: 'brush', text: 'Draw your best idea so others can see it.', example: 'A sketch of a bin with a foot pedal press.' },
  Make: { icon: 'hammer', text: 'Build a small model with paper, cardboard or bottles.', example: 'A cardboard bin with a lid that presses down.' },
  Try: { icon: 'flask', text: 'Test your model. Does it work?', example: 'Fill it with paper and press. Did it squash?' },
  Change: { icon: 'refresh', text: 'Fix what did not work and try again.', example: 'Make the lid stronger with two layers.' },
  Share: { icon: 'megaphone', text: 'Show your invention and tell its story.', example: 'Present it to your class.' },
  Observe: { icon: 'eye', text: 'Watch real situations closely and write down what you see.', example: 'Taps are left running after lunch.' },
  Identify: { icon: 'search', text: 'Turn what you saw into one clear problem sentence.', example: 'Students waste water at school taps after lunch.' },
  Why: { icon: 'git-branch', text: 'Ask "why?" five times to find the root cause.', example: 'Why? The taps are hard to close fully.' },
  Ideate: { icon: 'bulb', text: 'List at least 5 different solutions before choosing.', example: 'Self-closing tap, reminder sign, bottle refill station…' },
  SCAMPER: { icon: 'color-wand', text: 'Twist ideas: Substitute, Combine, Adapt, Modify, Put to other use, Eliminate, Reverse.', example: 'Combine a bottle and string to make a self-closing tap.' },
  Prototype: { icon: 'construct', text: 'Build it, or design it on paper if you have no materials.', example: 'A tap handle with a weighted string that pulls it shut.' },
  Test: { icon: 'flask', text: 'Predict, test, and record what happened, including failures.', example: 'Closed 9 out of 10 times. The string slipped once.' },
  Improve: { icon: 'trending-up', text: 'Use your test results to make version 2 better.', example: 'Tie the string with a double knot.' },
  Research: { icon: 'library', text: 'Find out who is affected and what already exists.', example: 'Interview 10 farmers about grain storage losses.' },
  'Root cause': { icon: 'git-branch', text: 'Dig past symptoms to the cause you can actually change.', example: 'Moisture gets into sacks stored on the floor.' },
  Feasibility: { icon: 'calculator', text: 'Check cost, materials, skills and time honestly.', example: 'Raised pallets cost ₦2,000 and use local wood.' },
  Validation: { icon: 'checkmark-done', text: 'Test with real users and measure the results.', example: '5 farmers used it for a month; losses fell by 30%.' },
  Impact: { icon: 'earth', text: 'Measure the difference for people and the environment.', example: 'Saves 200kg of maize per farmer per season.' },
  'Advanced prototyping': { icon: 'rocket', text: 'Build a refined version ready to share or sell.', example: 'A stackable pallet design with a cost sheet.' },
};
